apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tech-challenge-app.fullname" . }}
  labels:
    {{- include "tech-challenge-app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tech-challenge-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tech-challenge-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tech-challenge-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: {{ .Values.image.command }} # Issue here, I can't manage to get the values.yaml command value to not get mangled (loosing quotes)
          #command: ["./TechChallengeApp","updatedb","-s", "&&", "./TechChallengeApp","serve"]
          command: ["/bin/sh","-c"]
          args: ["./TechChallengeApp updatedb -s && ./TechChallengeApp serve"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "tech-challenge-app.fullname" . }}-configmap
            - secretRef:
                name: {{ include "tech-challenge-app.fullname" . }}-secrets
          livenessProbe:
            httpGet:
              path: /healthcheck/
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
