apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "tech-challenge-app.fullname" . }}-db-migrations-{{ .Chart.AppVersion }}-secrets"
  labels:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
data:
  VTT_DBPASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
