apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tech-challenge-app.fullname" . }}-secrets
  labels:
    {{- include "tech-challenge-app.labels" . | nindent 4 }}
type: Opaque
data:
  VTT_DBPASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
